plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}" apply false
	id 'net.neoforged.moddev' version "${moddev_version}" apply false
}

subprojects {
	apply plugin: 'java'
	apply plugin: 'maven-publish'

	ext.minecraftMajor = rootProject.minecraft_version.tokenize('.').take(2).join('.')
	version = "${rootProject.mod_version}+${rootProject.minecraft_version}"
	group = rootProject.maven_group

	java {
		withSourcesJar()

		toolchain {
			languageVersion = JavaLanguageVersion.of(25)
		}
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = 25
	}

	tasks.withType(AbstractArchiveTask).configureEach {
		archiveVersion = rootProject.mod_version
	}
}
